# Apache server used to host the UI pages
# Port mapping should be 8080:80
FROM httpd:2.4
COPY ../fonts/ /usr/local/apache2/htdocs/fonts/
COPY ../Images/ /usr/local/apache2/htdocs/Images/
COPY ../UI/ /usr/local/apache2/htdocs/UI/